### ISSUE TITLE
Escaped XML/HTML characters displaying improperly.

### ISSUE THREAD

**Issue by JoshTheDerf** [todevelopers/gnome-shell-extension-rss-feed#2]
I'm not sure how hard this would be to fix, but many RSS feeds contain XML/HTML escaped codes, such as `&amp;, &quot;, &nbsp;` etc. All of these are displayed raw in the feed reader, making it a bit painful to read for certain feeds.

Otherwise, excellent extension! A must for my desktop. :)

**Comment by tommy-gun** [comment]
Thank you for your bug report. I didn`t know about this problem.
Should you attach in comment some of RSS feeds where this escaped codes occured?

**Comment by JoshTheDerf** [comment]
Here you go, this happens with any GitHub activity feed.
![image](https://cloud.githubusercontent.com/assets/5861371/7463867/e949da9c-f2ef-11e4-8746-5b0a3f93125d.png)

Thanks for replying so quickly!

**Comment by tommy-gun** [comment]
I found simple JavaScript library, that contains function to decode HTML escape characters: http://www.strictly-software.com/htmlencode
Be sure that in next version this bug will be fixed.

**Comment by JoshTheDerf** [comment]
@tommy-gun Excellent! Thanks a lot! Will close this issue when fixed.

**Comment by tommy-gun** [comment]
I close this issue after new version with this bugfix release. Thanks for your bug report, it really help makes RSS Feed better.

**Comment by tommy-gun** [comment]
Fixed in version 1.2
