### ISSUE TITLE
Behind proxy use

### ISSUE THREAD

**Issue by lours974** [todevelopers/gnome-shell-extension-rss-feed#4]
Hi,
For your extension working behind a proxy i add this line in extension.js line 292 : 

> _httpGetRequestAsync: function(url, params, position, callback) {
> 
> ```
>    if (this._httpSession == null)
>        this._httpSession = new Soup.SessionAsync();
> ```
> 
> \+     //Lours974 Vitry David
> +     // This makes the session work under a proxy. The funky syntax here
> +     // is required because of another libsoup quirk, where there's a gobject
> +     // property called 'add-feature', designed as a construct property for
> +     // C convenience.
> +     Soup.Session.prototype.add_feature.call(this._httpSession, new >Soup.ProxyResolverDefault());
> 
> ```
>    Log.Debug("[" + position + "] Soup HTTP GET request. URL: " + url + " parameters: " + JSON.stringify(params));
> ```

../..

Thanks

**Comment by tommy-gun** [comment]
Thank you, I will merge it into master branch. 
This change will appear in next release soon.

**Comment by tommy-gun** [comment]
If you want, you should give me your email contact and I add you to contributors list

**Comment by lours974** [comment]
Thank you : 

Vitry David
david.vitry@vitry974.net
Reunion Island

**Comment by tommy-gun** [comment]
Ok, it's done
